15.02.2020 20:15:29 Checking for system tray...
15.02.2020 20:15:29 Starting pgAdmin4 server...
15.02.2020 20:15:29 Creating server object, port:53266, key:ce115eff-23a2-48f7-9344-4c1ea0d2bf4b, logfile:/Users/mac/.pgAdmin4.15182351514808255573.log
15.02.2020 20:15:29 Python Path: /Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7:/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/lib-dynload:/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python3.7/site-packages
15.02.2020 20:15:29 Python Home: /Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv
15.02.2020 20:15:29 Initializing Python...
15.02.2020 20:15:29 Python initialized.
15.02.2020 20:15:29 Adding new additional path elements
15.02.2020 20:15:29 Redirecting stderr...
15.02.2020 20:15:29 stderr redirected successfully.
15.02.2020 20:15:29 Initializing server...
15.02.2020 20:15:29 Webapp Path: /Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/web/pgAdmin4.py
15.02.2020 20:15:29 Server initialized.
15.02.2020 20:15:29 Starting Server Thread...
15.02.2020 20:15:29 Open the application code and run it.
15.02.2020 20:15:29 Set the port number, key and force SERVER_MODE off
15.02.2020 20:15:29 PyRun_SimpleFile launching application server...
15.02.2020 20:15:30 Application Server URL: http://127.0.0.1:53266/?key=ce115eff-23a2-48f7-9344-4c1ea0d2bf4b
15.02.2020 20:15:30 The server should be up, we'll attempt to connect and get a response. Ping the server
15.02.2020 20:15:37 Attempt to connect one more time in case of a long network timeout while looping
15.02.2020 20:15:37 Everything works fine, successfully started pgAdmin4.
